my_silant/my_silant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backend.urls')),
    path('auth/', include('index_view.urls')),
    path('sign/', include('sign.urls'))
]

my_silant/sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('login/',
         LoginView.as_view(template_name = 'sign/login.html'),
         name='login'),
    path('logout/',
         LogoutView.as_view(template_name = 'sign/logout.html'),
         name='logout'),
]

my_silant/backend/models.py
from django.db import models
from django.contrib.auth.models import User


# class Base_dictionary(models.Model):
#     name = models.TextField(unique=True, verbose_name='Название')
#     description = models.TextField(blank=True, verbose_name='Описание')

#     class Meta:
#         abstract = True
        
#     def __str__(self):
#         return f'{self.name}'
    

class TechniqueModel(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/modeltech'

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Модель техники'
        verbose_name_plural = 'Модели техники'


class EngineModel(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/modeleng'

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Модель двигателя'
        verbose_name_plural = 'Модели двигателя'


class TransmissionModel(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/modeltrans'

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Модель трансмиссии'
        verbose_name_plural = 'Модели трансмиссии'


class DriveAxleModel(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/modelaxel'

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Модель ведущего моста'
        verbose_name_plural = 'Модели ведущего моста'


class SteerableAxleModel(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/modelsteer'

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Модель управляемого моста'
        verbose_name_plural = 'Модели управляемого моста'


class ServiceCompany(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/servisecomp'

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Сервисная компания'
        verbose_name_plural = 'Сервисные компании'
    

class Client(models.Model):
    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Имя пользователя')


class Car(models.Model):
    serial_number = models.TextField(max_length=55, unique=True, db_index=True, null=True, blank=True, verbose_name='Зав. № машины')
    technique_model = models.ForeignKey(TechniqueModel, on_delete=models.CASCADE, db_index=True, null=True, blank=True, verbose_name='Модель техники')
    engine_model = models.ForeignKey(EngineModel, on_delete=models.CASCADE, db_index=True, null=True, blank=True, verbose_name='Модель двигателя')
    engine_number = models.TextField(max_length=55, null=True, blank=True, verbose_name='Зав. № двигателя')
    transmission_model = models.ForeignKey(TransmissionModel, on_delete=models.CASCADE, db_index=True, null=True, blank=True, verbose_name='Модель трансмиссии')
    transmission_number = models.TextField(max_length=55, null=True, blank=True, verbose_name='Зав. № трансмиссии')
    drive_axle_model = models.ForeignKey(DriveAxleModel, on_delete=models.CASCADE, db_index=True, null=True, blank=True, verbose_name='Модель ведущего моста')
    drive_axle_number = models.TextField(max_length=55, verbose_name='Зав. № ведущего моста')
    steerable_axle_model = models.ForeignKey(SteerableAxleModel, on_delete=models.CASCADE, db_index=True, null=True, blank=True, verbose_name='Модель управляемого моста')
    steerable_axle_number = models.TextField(max_length=55, null=True, blank=True, verbose_name='Зав. № управляемого моста')
    supply_contract = models.TextField(max_length=55, null=True, blank=True, verbose_name='Договор поставки №, дата.')
    shipping_date = models.DateField(db_index=True, null=True, blank=True, verbose_name='Дата отгрузки с завода')
    consignee = models.TextField(max_length=55, null=True, blank=True, verbose_name='Грузополучатель (конечный потребитель)')
    delivery_address = models.TextField(max_length=255, null=True, blank=True, verbose_name='Адрес поставки (эксплуатации)')
    equipment = models.TextField(max_length=255, null=True, blank=True, verbose_name='Комплектация (доп. опции)')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Клиент')
    service_company = models.ForeignKey(ServiceCompany, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Сервисная организация')

    def __str__(self):
        return f'{self.serial_number}'
    
    def get_absolute_url(self):
        return f'/user'

    class Meta:
        verbose_name = 'Машины'
        verbose_name_plural = 'Машины'
        ordering = ['-shipping_date'] # Сортировка по дате отгрузки
        

class TypeMaintenance(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/maintenancetype'

    def __str__(self):
        return self.name


class OrganizationMaintenance(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/maintenanceorg'

    def __str__(self):
        return self.name
    
    class Meta:
         verbose_name = 'Организация, проводившая ТО'
         verbose_name_plural = 'Организации, проводившие ТО'


class Maintenance(models.Model):
    type_maintenance = models.ForeignKey(TypeMaintenance, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Вид ТО')
    maintenance_date = models.DateField(null=True, blank=True, verbose_name='Дата проведения ТО')
    operating_time = models.IntegerField(null=True, blank=True, verbose_name='Наработка м/час')
    order = models.TextField(max_length=55, null=True, blank=True, verbose_name='Номер заказа-наряда')
    order_date = models.DateField(verbose_name='Дата заказа-наряда')
    organization_maintenance = models.ForeignKey(OrganizationMaintenance, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Организация, проводившая ТО')
    car = models.ForeignKey(Car, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Машина')
    service_company = models.ForeignKey(ServiceCompany, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Сервисная компания')
    serial_number = models.TextField(max_length=55, unique=True, db_index=True, null=True, blank=True, verbose_name='Зав. № машины')

    def __str__(self):
        return f'{self.car}'
    
    def get_absolute_url(self):
        return f'/maintenance'

    class Meta:
        verbose_name = 'ТО'
        verbose_name_plural = 'ТО'      
        ordering = ['-maintenance_date']


class FailureNode(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/fnode'

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Узел отказа'
        verbose_name_plural = 'Узлы отказа'


class RecoveryMethod(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/reco'

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Способ восстановления'
        verbose_name_plural = 'Способы восстановления'


class Complaints(models.Model):
    date_of_refusal = models.DateField(null=True, blank=True, verbose_name='Дата отказа')
    operating_time = models.IntegerField(null=True, blank=True, verbose_name='Наработка м/час')
    failure_node = models.ForeignKey(FailureNode, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Узел отказа') 
    description_failure = models.TextField(max_length=1024, null=True, blank=True, verbose_name='Характер отказа')
    recovery_method = models.ForeignKey(RecoveryMethod, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Способ восстановления')
    parts_used = models.TextField(verbose_name='Используемые запасные части', null=True, blank=True)
    date_of_restoration = models.DateField(verbose_name='Дата восстановления') 
    equipment_downtime = models.IntegerField(verbose_name='Время простоя техники', null=True, blank=True, editable=True)
    car = models.ForeignKey(Car, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Машина')
    service_company = models.ForeignKey(ServiceCompany, on_delete=models.CASCADE, null=True, verbose_name='Сервисная организация')
    serial_number = models.TextField(max_length=55, unique=True, db_index=True, null=True, blank=True, verbose_name='Зав. № машины')

    def __str__(self):
        return f'{self.car}'
    
    def get_absolute_url(self):
        return f'/complaints'

    class Meta:
        verbose_name = 'Рекламации'
        verbose_name_plural = 'Рекламации'
        ordering = ['-date_of_refusal']

    # Расчетное поле для времени простоя техники: Дата восстановления - Дата отказа
    def save(self, *args, **kwargs):
        self.equipment_downtime = (self.date_of_restoration - self.date_of_refusal).days
        super(Complaints, self).save(*args, **kwargs)

my_silant/templates/CarCreate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

my_silant/templates/CarDetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

my_silant/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link rel="shortcut icon" href=/static/media/LogotypeBlue.jpg>
        <title>{% block head_title %}{% endblock head_title %}</title>

        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
    </head>
    <body>
        <div class="wrapper">
            <header class="p-3 bg-dark bg-silant-sands text-header">
                <div class="container">
                    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-header text-decoration-none">
                        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
                        </a>
                
                        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                            <li><img width="50px" height="50px" src="/static/media/LogotypeRed.jpg"></li>
                            <li><a href="/" class="nav-link px-2 text-secondary">СИЛАНТ</a></li>
                            <li><a href="tel:88352201209" class="nav-link px-2 text-header">+7 (835) 220-12-09</a></li>
                            <li><a href="https://t.me/chzsa21" class="nav-link px-2 text-header">telegram</a></li>
                        </ul>
                    </div>
                    <div class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                        <h1><b>Электронная сервисная книжка "Мой Силант"</b></h1>
                    </div>                    
                </div>
            </header>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">    
                            {% block body %}
                            {% block content %}
                            {% endblock content %}
                            {% endblock body %}
                            {% block extra_body %}
                            {% endblock extra_body %}
                        </div>
                    </div>
                </div>
                <div class="container">
                    <footer class="d-flex flex-wrap justify-content-between align-items-end py-3 my-4 border-top">
                        <ul class="nav col-md-4 justify-content-start mb-0 position-relative z-index-1">
                            <li class="nav-item"><a href="tel:88352201209" class="nav-link px-2 text-muted">+7 (835) 220-12-09</a></li>
                            <li class="nav-item"><a href="https://t.me/chzsa21" class="nav-link px-2 text-muted">telegram</a></li>
                        </ul>
                    
                        <p class="col-md-4 mb-0 position-relative text-muted">© 2022 МОЙ СИЛАНТ</p>
                    </footer>
                </div>
        </div>
  
    </body>
</html>

my_silant/templates/car_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

my_silant/templates/car_detail.html
{% extends 'flatpages/default.html' %}
{% load static %}

{% block title %}
cars
{% endblock title %}

{% block content %}
    <h1>Просмотр информации о машине с серийным номером № {{ car.serial_number  }}</h1>
    <div class="container">
        <div class="row">
          <div class="col">
            <a class="btn btn-silant-red">Общая информация</a>
          </div>
          <div class="col">
            <a class="btn btn-silant-blue" href="maintenances/?car={{car.id}}">ТО</a>
          </div>
          <div class="col">
            <a class="btn btn-silant-blue" href="complaints/?car={{car.id}}">Рекламации</a>
          </div>
        </div>
    </div>
    <div>
    <table class="table">
        <thead>
            <tr>                                                                 
                <th scope="col">Зав. № машины</th>
                <th scope="col">Модель техники</th>
                <th scope="col">Модель двигателя</th>
                <th scope="col">Зав. № двигателя</th>
                <th scope="col">Модель трансмиссии</th>
                <th scope="col">Зав. № трансмиссии</th>
                <th scope="col">Модель ведущего моста</th>
                <th scope="col">Зав. № ведущего моста</th>
                <th scope="col">Модель управляемого моста</th>
                <th scope="col">Зав. № управляемого моста</th>
                <th scope="col">Договор поставки №, дата</th>
                <th scope="col">Дата отгрузки с завода</th>
                <th scope="col">Грузополучатель (конечный потребитель)</th>
                <th scope="col">Адрес поставки (эксплуатации)</th>
                <th scope="col">Комплектация (доп. опции)</th>
                <th scope="col">Клиент</th>
                <th scope="col">Сервисная организация</th>
                {% if perms.silant.change_car %}
                  <th scope="col">Операции</th>
                {% endif %} 
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ car.serial_number }}</td>
                <td><a href="dictionary/techniqueModel/{{car.technique_model.id}}/">{{ car.technique_model }}</a></td>
                <td><a href="dictionary/engineModel/{{car.engine_model.id}}/">{{ car.engine_model }}</a></td>
                <td>{{ car.engine_number }}</td>
                <td><a href="dictionary/transmissionModel/{{car.transmission_model.id}}/">{{ car.transmission_model }}</a></td>
                <td>{{ car.transmission_number }}</td>
                <td><a href="dictionary/driveAxleModel/{{car.drive_axle_model.id}}/">{{ car.drive_axle_model }}</a></td>
                <td>{{ car.drive_axle_number }}</td>
                <td><a href="dictionary/steerableAxleModel/{{car.steerable_axle_model.id}}/">{{ car.steerable_axle_model }}</a></td>
                <td>{{ car.steerable_axle_number }}</td>
                <td>{{ car.supply_contract }}</td>
                <td>{{ car.shipping_date }}</td>
                <td>{{ car.consignee }}</td>
                <td>{{ car.delivery_address }}</td>
                <td>{{ car.equipment }}</td>
                <td>{{ car.client }}</td>
                <td><a href="dictionary/ServiceCompany/{{car.service_company.id}}/">{{ car.service_company }}</a></td>
                {% if perms.silant.change_car %}
                  <td>                 
                    <a class="btn btn-silant-blue" href="/cars/edit/{{car.id}}">Изменить</a>
                  </td>
                {% endif %}   
            </tr>
        </tbody>
    </table>
    {% endblock content %}

my_silant/templates/cars.html
{% extends 'flatpages/default.html' %}

{% block title %}
cars
{% endblock title %}

{% block content %}
    <h2><b>Проверьте комплектацию и технические характеристики техники Силант</b></h2>
    {% if user.is_authenticated %}
        <div class="container">
            <div class="row">
                <div class="col">
                    <a class="btn btn-silant-red">Общая информация</a>
                </div>
                <div class="col">
                    <a class="btn btn-silant-blue" href="/cars/maintenances/">ТО </a>
                </div>
                <div class="col">
                    <a class="btn btn-silant-blue" href="/cars/complaints/">Рекламации</a>
                </div>
            </div>
        </div>
    {% endif %}
    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input class="btn btn-silant-blue" type="submit" value="Найти" />
    </form>
    <hr>
    
    {% if cars %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Зав. № машины</th>
                    <th scope="col">Модель техники</th>
                    <th scope="col">Модель двигателя</th>
                    <th scope="col">Зав. № двигателя</th>
                    <th scope="col">Модель трансмиссии</th>
                    <th scope="col">Зав. № трансмиссии</th>
                    <th scope="col">Модель ведущего моста</th>
                    <th scope="col">Зав. № ведущего моста</th>
                    <th scope="col">Модель управляемого моста</th>
                    <th scope="col">Зав. № управляемого моста</th>
                    {% if user.is_authenticated %}
                        <th scope="col">Договор поставки №, дата</th>
                        <th scope="col">Дата отгрузки с завода</th>
                        <th scope="col">Грузополучатель (конечный потребитель)</th>
                        <th scope="col">Адрес поставки (эксплуатации)</th>
                        <th scope="col">Комплектация (доп. опции)</th>
                        <th scope="col">Клиент</th>
                        <th scope="col">Сервисная организация</th>
                        <th scope="col">Операции</th>
                    {% endif %}    
                </tr>
            </thead>
            <tbody>
            {% for car in cars %}
                <tr>
                    <td>{{ car.serial_number }}</td>
                    <td><a href="dictionary/techniqueModel/{{car.technique_model.id}}/">{{ car.technique_model }}</a></td>
                    <td><a href="dictionary/engineModel/{{car.engine_model.id}}/">{{ car.engine_model }}</a></td>
                    <td>{{ car.engine_number }}</td>
                    <td><a href="dictionary/transmissionModel/{{car.transmission_model.id}}/">{{ car.transmission_model }}</a></td>
                    <td>{{ car.transmission_number }}</td>
                    <td><a href="dictionary/driveAxleModel/{{car.drive_axle_model.id}}/">{{ car.drive_axle_model }}</a></td>
                    <td>{{ car.drive_axle_number }}</td>
                    <td><a href="dictionary/steerableAxleModel/{{car.steerable_axle_model.id}}/">{{ car.steerable_axle_model }}</a></td>
                    <td>{{ car.steerable_axle_number }}</td>
                    {% if user.is_authenticated %}
                        <td>{{ car.supply_contract }}</td>
                        <td>{{ car.shipping_date }}</td>
                        <td>{{ car.consignee }}</td>
                        <td>{{ car.delivery_address }}</td>
                        <td style="white-space: pre-line;">{{ car.equipment }}</td>
                        <td>{{ car.client }}</td>
                        <td><a href="dictionary/ServiceCompany/{{car.service_company.id}}/">{{ car.service_company }}</a></td>
                        <td>
                            <a class="btn btn-silant-blue" href="/cars/{{car.id}}">Подробнее</a>
                            {% if perms.silant.change_car %} 
                                <a class="btn btn-silant-blue" href="/cars/edit/{{car.id}}">Изменить</a>
                            {% endif %} 
                        </td>
                    {% endif %}                    
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h2>Машин нет</h2>
    {% endif %}

    {% if page_obj.has_previous %}
        <a href="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

    <div class="container">
        <div class="row">
            {% if perms.silant.add_car %}
                <div class="col">
                    <a class="btn btn-silant-blue" href="create/">Добавить машину</a>
                </div>
            {% endif %}    
        </div>
    </div>
{% endblock content %}

my_silant/templates/dict.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>{{namegroup}}</h1>

<form action="/cars/dictionary/save/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input name="id" type="hidden" value="{{item.id}}">
    <input name="type" type="hidden" value="{{type}}">     
    <div>
        <label>
            <b>Наименование</b>
        </label>
        {% if perms.silant.add_car %}
            <textarea name="name" maxlength="30" required="" id="id_name" class="form-control text-black text-center">{{ item.name }}</textarea>
        {% else %}
            <textarea name="name" maxlength="30" required="" id="id_name" class="form-control text-black text-center" disabled>{{ item.name }}</textarea>
        {% endif %}
    </div>
    <div>
        <label>
            <b>Описание</b>
        </label>
        {% if perms.silant.add_car %}
            <textarea name="description" maxlength="100" required="" id="id_description" class="form-control text-black text-center">{{ item.description }}</textarea>
        {% else %}
            <textarea name="description" maxlength="100" required="" id="id_description" class="form-control text-black text-center" disabled>{{ item.description }}</textarea>
        {% endif %}
    </div>
    {% if perms.silant.add_car %}
        <button type="submit" class="btn btn-silant-blue">Сохранить</button>
    {% endif %}
    <h1></h1>
    <div>
        <a href="javascript:history.back()" class="btn btn-silant-blue">Вернуться на прошлую страницу</a>
    </div>

</form>


{% endblock content %}

my_silant/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html lang="en">
    <body>
    {% block content %}
        <h2>Добро пожаловать! {{request.user.username}}</h2>
        <button> <a href="sign/logout/">Выйти</a> </button>
    {% endblock content %}
    </body>
</html>

my_silant/templates/search.html
{% extends 'flatpages/default.html' %}

{% block title %}
cars
{% endblock title %}

{% block content %}
    <h2><b>Проверьте комплектацию и технические характеристики техники Силант</b></h2>
    {% if user.is_authenticated %}
        <div class="container">
            <div class="row">
                <div class="col">
                    <a class="btn btn-silant-red">Общая информация</a>
                </div>
                <div class="col">
                    <a class="btn btn-silant-blue" href="/cars/maintenances/">ТО </a>
                </div>
                <div class="col">
                    <a class="btn btn-silant-blue" href="/cars/complaints/">Рекламации</a>
                </div>
            </div>
        </div>
    {% endif %}
    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input class="btn btn-silant-blue" type="submit" value="Найти" />
    </form>
    <hr>
    
    {% if cars %}
    <table class="table">
        <tbody>
            <tr>
                <th scope="col">Зав. № машины</th>
                <th scope="col">Модель техники</th>
                <th scope="col">Модель двигателя</th>
                <th scope="col">Зав. № двигателя</th>
                <th scope="col">Модель трансмиссии</th>
                <th scope="col">Зав. № трансмиссии</th>
                <th scope="col">Модель ведущего моста</th>
                <th scope="col">Зав. № ведущего моста</th>
                <th scope="col">Модель управляемого моста</th>
                <th scope="col">Зав. № управляемого моста</th>
                {% if user.is_authenticated %}
                    <th scope="col">Договор поставки №, дата</th>
                    <th scope="col">Дата отгрузки с завода</th>
                    <th scope="col">Грузополучатель (конечный потребитель)</th>
                    <th scope="col">Адрес поставки (эксплуатации)</th>
                    <th scope="col">Комплектация (доп. опции)</th>
                    <th scope="col">Клиент</th>
                    <th scope="col">Сервисная организация</th>
                    <th scope="col">Операции</th>
                {% endif %}    
            </tr>
        <tbody>
        {% for car in cars %}
            <tr>
                <td>{{car.serial_number}}</td>
                <td>{{ car.technique_model }}</a></td>
                <td>{{ car.engine_model }}</a></td>
                <td>{{ car.engine_number }}</td>
                <td>{{ car.transmission_model }}</a></td>
                <td>{{ car.transmission_number }}</td>
                <td>{{ car.drive_axle_model }}</a></td>
                <td>{{ car.drive_axle_number }}</td>
                <td>{{ car.steerable_axle_model }}</a></td>
                <td>{{ car.steerable_axle_number }}</td>
                {% if user.is_authenticated %}
                    <td>{{ car.supply_contract }}</td>
                    <td>{{ car.shipping_date }}</td>
                    <td>{{ car.consignee }}</td>
                    <td>{{ car.delivery_address }}</td>
                    <td style="white-space: pre-line;">{{ car.equipment }}</td>
                    <td>{{ car.client }}</td>
                    <td>{{ car.service_company }}</a></td>
                    <td>
                        <a class="btn btn-silant-blue" href="/cars/{{car.id}}">Подробнее</a>
                        {% if perms.silant.change_car %} 
                            <a class="btn btn-silant-blue" href="/cars/edit/{{car.id}}">Изменить</a>
                        {% endif %} 
                    </td>
                {% endif %}                    
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <h2>Машин нет</h2>
{% endif %}

    {% if page_obj.has_previous %}
        <a href="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

    <div class="container">
        <div class="row">
            {% if perms.silant.add_car %}
                <div class="col">
                    <a class="btn btn-silant-blue" href="create/">Добавить машину</a>
                </div>
            {% endif %}    
        </div>
    </div>
{% endblock content %}