my_silant/my_silant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backend.urls')),
    path('auth/', include('index_view.urls')),
    path('sign/', include('sign.urls'))
]

my_silant/sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('login/',
         LoginView.as_view(template_name = 'sign/login.html'),
         name='login'),
    path('logout/',
         LogoutView.as_view(template_name = 'sign/logout.html'),
         name='logout'),
]

my_silant/backend/models.py
from django.db import models
from django.contrib.auth.models import User


# class Base_dictionary(models.Model):
#     name = models.TextField(unique=True, verbose_name='Название')
#     description = models.TextField(blank=True, verbose_name='Описание')

#     class Meta:
#         abstract = True
        
#     def __str__(self):
#         return f'{self.name}'
    

class TechniqueModel(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/modeltech'

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Модель техники'
        verbose_name_plural = 'Модели техники'


class EngineModel(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/modeleng'

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Модель двигателя'
        verbose_name_plural = 'Модели двигателя'


class TransmissionModel(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/modeltrans'

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Модель трансмиссии'
        verbose_name_plural = 'Модели трансмиссии'


class DriveAxleModel(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/modelaxel'

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Модель ведущего моста'
        verbose_name_plural = 'Модели ведущего моста'


class SteerableAxleModel(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/modelsteer'

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Модель управляемого моста'
        verbose_name_plural = 'Модели управляемого моста'


class ServiceCompany(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/servisecomp'

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Сервисная компания'
        verbose_name_plural = 'Сервисные компании'
    

class Client(models.Model):
    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Имя пользователя')


class Car(models.Model):
    serial_number = models.TextField(max_length=55, unique=True, db_index=True, null=True, blank=True, verbose_name='Зав. № машины')
    technique_model = models.ForeignKey(TechniqueModel, on_delete=models.CASCADE, db_index=True, null=True, blank=True, verbose_name='Модель техники')
    engine_model = models.ForeignKey(EngineModel, on_delete=models.CASCADE, db_index=True, null=True, blank=True, verbose_name='Модель двигателя')
    engine_number = models.TextField(max_length=55, null=True, blank=True, verbose_name='Зав. № двигателя')
    transmission_model = models.ForeignKey(TransmissionModel, on_delete=models.CASCADE, db_index=True, null=True, blank=True, verbose_name='Модель трансмиссии')
    transmission_number = models.TextField(max_length=55, null=True, blank=True, verbose_name='Зав. № трансмиссии')
    drive_axle_model = models.ForeignKey(DriveAxleModel, on_delete=models.CASCADE, db_index=True, null=True, blank=True, verbose_name='Модель ведущего моста')
    drive_axle_number = models.TextField(max_length=55, verbose_name='Зав. № ведущего моста')
    steerable_axle_model = models.ForeignKey(SteerableAxleModel, on_delete=models.CASCADE, db_index=True, null=True, blank=True, verbose_name='Модель управляемого моста')
    steerable_axle_number = models.TextField(max_length=55, null=True, blank=True, verbose_name='Зав. № управляемого моста')
    supply_contract = models.TextField(max_length=55, null=True, blank=True, verbose_name='Договор поставки №, дата.')
    shipping_date = models.DateField(db_index=True, null=True, blank=True, verbose_name='Дата отгрузки с завода')
    consignee = models.TextField(max_length=55, null=True, blank=True, verbose_name='Грузополучатель (конечный потребитель)')
    delivery_address = models.TextField(max_length=255, null=True, blank=True, verbose_name='Адрес поставки (эксплуатации)')
    equipment = models.TextField(max_length=255, null=True, blank=True, verbose_name='Комплектация (доп. опции)')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Клиент')
    service_company = models.ForeignKey(ServiceCompany, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Сервисная организация')

    def __str__(self):
        return f'{self.serial_number}'
    
    def get_absolute_url(self):
        return f'/user'

    class Meta:
        verbose_name = 'Машины'
        verbose_name_plural = 'Машины'
        ordering = ['-shipping_date'] # Сортировка по дате отгрузки
        

class TypeMaintenance(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/maintenancetype'

    def __str__(self):
        return self.name


class OrganizationMaintenance(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/maintenanceorg'

    def __str__(self):
        return self.name
    
    class Meta:
         verbose_name = 'Организация, проводившая ТО'
         verbose_name_plural = 'Организации, проводившие ТО'


class Maintenance(models.Model):
    type_maintenance = models.ForeignKey(TypeMaintenance, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Вид ТО')
    maintenance_date = models.DateField(null=True, blank=True, verbose_name='Дата проведения ТО')
    operating_time = models.IntegerField(null=True, blank=True, verbose_name='Наработка м/час')
    order = models.TextField(max_length=55, null=True, blank=True, verbose_name='Номер заказа-наряда')
    order_date = models.DateField(verbose_name='Дата заказа-наряда')
    organization_maintenance = models.ForeignKey(OrganizationMaintenance, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Организация, проводившая ТО')
    car = models.ForeignKey(Car, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Машина')
    service_company = models.ForeignKey(ServiceCompany, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Сервисная компания')
    serial_number = models.TextField(max_length=55, unique=True, db_index=True, null=True, blank=True, verbose_name='Зав. № машины')

    def __str__(self):
        return f'{self.car}'
    
    def get_absolute_url(self):
        return f'/maintenance'

    class Meta:
        verbose_name = 'ТО'
        verbose_name_plural = 'ТО'      
        ordering = ['-maintenance_date']


class FailureNode(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/fnode'

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Узел отказа'
        verbose_name_plural = 'Узлы отказа'


class RecoveryMethod(models.Model):
    name = models.TextField(verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def get_absolute_url(self):
        return f'/reco'

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Способ восстановления'
        verbose_name_plural = 'Способы восстановления'


class Complaints(models.Model):
    date_of_refusal = models.DateField(null=True, blank=True, verbose_name='Дата отказа')
    operating_time = models.IntegerField(null=True, blank=True, verbose_name='Наработка м/час')
    failure_node = models.ForeignKey(FailureNode, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Узел отказа') 
    description_failure = models.TextField(max_length=1024, null=True, blank=True, verbose_name='Характер отказа')
    recovery_method = models.ForeignKey(RecoveryMethod, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Способ восстановления')
    parts_used = models.TextField(verbose_name='Используемые запасные части', null=True, blank=True)
    date_of_restoration = models.DateField(verbose_name='Дата восстановления') 
    equipment_downtime = models.IntegerField(verbose_name='Время простоя техники', null=True, blank=True, editable=True)
    car = models.ForeignKey(Car, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Машина')
    service_company = models.ForeignKey(ServiceCompany, on_delete=models.CASCADE, null=True, verbose_name='Сервисная организация')
    serial_number = models.TextField(max_length=55, unique=True, db_index=True, null=True, blank=True, verbose_name='Зав. № машины')

    def __str__(self):
        return f'{self.car}'
    
    def get_absolute_url(self):
        return f'/complaints'

    class Meta:
        verbose_name = 'Рекламации'
        verbose_name_plural = 'Рекламации'
        ordering = ['-date_of_refusal']

    # Расчетное поле для времени простоя техники: Дата восстановления - Дата отказа
    def save(self, *args, **kwargs):
        self.equipment_downtime = (self.date_of_restoration - self.date_of_refusal).days
        super(Complaints, self).save(*args, **kwargs)

my_silant/templates/maintenance/create_maintenance.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Создание/Редактирование записи ТО</h1>
<hr>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_ul }}
    <button class="btn btn-silant-blue" type="submit">Сохранить</button>
</form>

{% endblock content %}

my_silant/templates/maintenance/maintenances.html
{% extends 'flatpages/default.html' %}

{% block title %}
maintenances
{% endblock title %}

{% block content %}
    <h2><b>Техническое обслуживание машины</b></h2>
    {% if user.is_authenticated %}
    <div class='container'>
        <div class='row'>
        <div class='col'>
            <a class='btn btn-silant-blue' href='/cars/'>Общая информация</a>
        </div>
        <div class='col'>
            <a class='btn btn-silant-red'>ТО</a>
        </div>
        <div class='col'>
            <a class='btn btn-silant-blue' href='/cars/complaints/?car={{maintenance.car.id}}'>Рекламации</a>
        </div>
        </div>
    </div>
    {% endif %}
    <form action='' method='get'>
            {{ filterset.form.as_p }}
            <input class='btn btn-silant-blue' type='submit' value='Найти' />
        </form>
    <hr>
    {% if maintenances %}
        <table class='table'>
            <thead>
                <tr>
                    <th scope='col'>Вид ТО</td>
                    <th scope='col'>Дата проведения ТО</td>
                    <th scope='col'>Наработка м/час</td>
                    <th scope='col'>№ заказа-наряда</td>
                    <th scope='col'>Дата заказа-наряда</td>
                    <th scope='col'>Организация, проводившая ТО</td>
                    <th scope='col'>Машина</td>
                    <th scope='col'>Сервисная организация</td>
                    {% if perms.silant.change_maintenance %}         
                        <th scope='col'>Операции</td>
                    {% endif %} 
                </tr>
            </thead>
            {% for maintenance in maintenances %}
                <tbody>
                    <tr>
                        <td><a href='dictionary/typeMaintenance/{{maintenance.type_maintenance.id}}/'>{{ maintenance.type_maintenance }}</a></td>
                        <td>{{ maintenance.maintenance_date }}</a></td>
                        <td>{{ maintenance.operating_time }}</a></td>
                        <td>{{ maintenance.order }}</td>
                        <td>{{ maintenance.order_date }}</a></td>
                        <td><a href='dictionary/organizationMaintenance/{{maintenance.organization_maintenance.id}}/'>{{ maintenance.organization_maintenance }}</a></td>
                        <td>{{ maintenance.car }}</a></td>
                        <td><a href='dictionary/serviceCompany/{{maintenance.service_company.id}}/'>{{ maintenance.service_company }}</a></td>
                        {% if perms.silant.change_maintenance %}
                            <td>
                                <a class='btn btn-silant-blue' href='/cars/maintenances/edit/{{maintenance.id}}'>Изменить</a>
                            </td>
                        {% endif %} 
                    </tr>
                </tbody>
            {% endfor %}
        </table>
    {% else %}
        <h2>Данных пока нет</h2>
    {% endif %}

    {% if page_obj.has_previous %}
        <a href='?page=1'>1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href='?page={{ page_obj.previous_page_number }}'>{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href='?page={{ page_obj.next_page_number }}'>{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href='?page={{ page_obj.paginator.num_pages }}'>{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
    <div class='container'>
        <div class='row'>
            {% if perms.silant.add_maintenance %}
                <div class='col'>
                    <a class='btn btn-silant-blue' href='/cars/maintenances/create/'>Создать ТО</a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}